# Generated by Django 5.2.3 on 2025-06-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamaño', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.adoptante')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.perro')),
            ],
        ),
    ]
