# Generated by Django 5.2.3 on 2025-07-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_perros'),
        ),
    ]
