# Generated by Django 5.2.3 on 2025-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_perro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='img',
            field=models.ImageField(null=True, upload_to='img_perros'),
        ),
    ]
