# Generated by Django 5.2.3 on 2025-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0005_alter_perro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('1', 'Chico'), ('2', 'Mediano'), ('3', 'Grande')], max_length=1),
        ),
    ]
