# Generated by Django 5.2.3 on 2025-07-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0006_alter_perro_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(blank=True, default='No incluye descripcion', null=True),
        ),
    ]
