# Generated by Django 5.2.3 on 2025-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0007_alter_perro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(blank=True, default='No incluye descripcion', max_length=50, null=True),
        ),
    ]
