# Generated by Django 5.2.3 on 2025-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0008_alter_perro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='img',
            field=models.ImageField(default='https://res.cloudinary.com/dk7buww21/image/upload/v123456789/default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
