# Generated by Django 5.2.3 on 2025-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0009_alter_perro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='img',
            field=models.ImageField(blank=True, default='img_perros/default.jpg', null=True, upload_to='img_perros'),
        ),
    ]
