# Generated by Django 5.2.3 on 2026-05-25 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0010_alter_perro_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='nombre',
        ),
        migrations.AddField(
            model_name='adoptante',
            name='actividad_fisica',
            field=models.BooleanField(default=False, help_text='¿Busca un perro para hacer actividad intensa/correr?'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tiempo_disponible',
            field=models.CharField(choices=[('bajo', 'Poco tiempo (menos de 1 hora al día)'), ('medio', 'Tiempo moderado (1 a 2 horas al día)'), ('alto', 'Mucho tiempo (más de 2 horas al día)')], default='medio', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tiene_niños',
            field=models.BooleanField(default=False, help_text='¿Viven niños en el hogar?'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tiene_otras_mascotas',
            field=models.BooleanField(default=False, help_text='¿Tiene otros perros o gatos?'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tipo_vivienda',
            field=models.CharField(choices=[('casa_patio', 'Casa con patio/jardín'), ('casa_sin_patio', 'Casa sin patio'), ('depto_grande', 'Departamento grande'), ('depto_chico', 'Departamento chico')], default='casa_patio', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_adoptante', to=settings.AUTH_USER_MODEL),
        ),
    ]
