# Generated by Django 5.2.3 on 2026-05-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0011_remove_adoptante_email_remove_adoptante_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADO', 'Adoptado definitivamente'), ('RECHAZADO', 'Solicitud rechazada')], default='PENDIENTE', max_length=50),
        ),
    ]
